apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-network-tester-demo
  namespace: demos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-network-tester-demo
  template:
    metadata:
      labels:
        app: webapp-network-tester-demo
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - image: jannemattila/webapp-network-tester
          name: webapp-network-tester-demo
          env:
            - name: ASPNETCORE_URLS
              value: http://*:8080
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 150m
              memory: 150Mi
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
