apiVersion: v1
kind: Service
metadata:
  name: webapp-network-tester-demo
  namespace: demos
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: webapp-network-tester-demo
